# Generated by Django 5.2.8 on 2025-12-04 17:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='forma_recinto',
            field=models.CharField(choices=[('triangulo', 'Triángulo'), ('cuadrado', 'Cuadrado'), ('rectangulo', 'Rectángulo'), ('circulo', 'Círculo'), ('hexagono', 'Hexágono'), ('octagono', 'Octágono')], default='cuadrado', max_length=20),
        ),
        migrations.AddField(
            model_name='evento',
            name='precio_avanzado',
            field=models.DecimalField(decimal_places=2, default=Decimal('180.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='evento',
            name='precio_normal',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='evento',
            name='precio_vip',
            field=models.DecimalField(decimal_places=2, default=Decimal('300.00'), max_digits=10),
        ),
    ]
