# Generated by Django 5.2.8 on 2025-12-04 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asientos', '0001_initial'),
        ('eventos', '0002_evento_forma_recinto_evento_precio_avanzado_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asiento',
            unique_together={('evento', 'fila', 'numero')},
        ),
    ]
